### ISSUE TITLE
clarification - on how midi device readings can persist over app life cycle

### ISSUE THREAD

**Issue by johndpope** [prevuelta/MIDIOverlord#2]
Hey Pablo,
This should probably be directed to MIKMidi - but maybe you know - or have had this problem.

I have a simple dj midi controller / some dials / nobs.
I can pan these faders to left / right and hook into these changes by listening  to midi commands -  and app can respond.

But how can query device for a reading of all the current settings? 
Is this a sysex message? 

If the pan is panned - and app restarts - 
how can I read the values if there's no midi signals being sent?
Or is your code saving all the values - and recalling them - irrespective of the physical nobs?

JP

**Comment by prevuelta** [comment]
HI John,

Do you mean the MIDIOverlord app? functionality is pretty limited at the
moment as still early stages - only reads cc  / note messages.

But generally would depend on the midi controller and whether it supports
sysex messages. I know with my synths it is a sysex (system exclusive)
message that then returns all the values for the patch at that location
(bank, program). Supporting sysex in the app will be a bigger challenge as
each manufacturer has a different implementation.

Hope that helps,
Pablo.

On Tue, Oct 20, 2015 at 5:41 PM, John Pope notifications@github.com wrote:

> Hey Pablo,
> This should probably be directed to MIKMidi - but maybe you know - or have
> had this problem.
> 
> I have a simple dj midi controller / some dials / nobs.
> I can pan these faders to left / right and hook into these changes by
> listening to midi commands - and app can respond.
> 
> But how can query device for a reading of all the current settings?
> Is this a sysex message?
> 
> If the pan is panned - and app restarts -
> how can I read the values if there's no midi signals being sent?
> Or is your code saving all the values - and recalling them - irrespective
> of the physical nobs?
> 
> JP
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/prevuelta/MIDIOverlord/issues/2.

## 

Pablo Revuelta

P: 022 694 4326
E: hello@pablorevuelta.com
W: www.pablorevuelta.com

**Comment by johndpope** [comment]
Hi Pablo,
I was searching through midi learn code - and found this 
![screen shot 2015-10-21 at 11 26 29 pm](https://cloud.githubusercontent.com/assets/289994/10636455/a64c25b0-784b-11e5-8ed5-af32f50d66ca.png)
https://github.com/zakk4223/CocoaSplit
Zak is using some commands to record / midi learn / there's also a csmidiwrapper that I've been able to re-purpose.  

After - re-reading what your app intends to do - 
For a standard midi note on / note off command - a receive note can be mapped to multiple send notes eg. D1 to a chord (C, E, G)

you may be interested in my app http://komposer.io/ hockeyapp download link available
(I'm have some known issues with El Capitan)

**Comment by johndpope** [comment]
hi @prevuelta  - closing this as a spring cleaning exercise. Thanks for your efforts.
